//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlliedAdapter.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.4.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://irisprodwebsuiteclone.abl.com.pk/WSInstantCard/InstantCard.asmx")]
        public string AlliedAdapter_WebReference_InstantCard {
            get {
                return ((string)(this["AlliedAdapter_WebReference_InstantCard"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://irisprodwebsuiteclone.abl.com.pk/WSInstantCard/InstantCard.asmx")]
        public string AlliedAdapter_WebReference1_InstantCard {
            get {
                return ((string)(this["AlliedAdapter_WebReference1_InstantCard"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://10.224.20.27:7815/ATMMSGSetSOAP_HTTP_Service")]
        public string AlliedAdapter_BioService_ATMMSGSetSOAP_HTTP_Service {
            get {
                return ((string)(this["AlliedAdapter_BioService_ATMMSGSetSOAP_HTTP_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://10.136.0.3/wsABLCARDSTATUSCHANGE/wsABLCARDSTATUSCHANGE.asmx")]
        public string AlliedAdapter_CardListing_wsABLCARDSTATUSCHANGE {
            get {
                return ((string)(this["AlliedAdapter_CardListing_wsABLCARDSTATUSCHANGE"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://192.168.51.13:8080/smpp_ws/smpp_ws_sendsms")]
        public string AlliedAdapter_AlliedSMSService_smpp_ws_sendsms {
            get {
                return ((string)(this["AlliedAdapter_AlliedSMSService_smpp_ws_sendsms"]));
            }
        }
    }
}
