//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MalawiAdapter.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Request", Namespace="http://schemas.datacontract.org/2004/07/RapidFileService.Contracts")]
    [System.SerializableAttribute()]
    public partial class Request : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SessionidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] DigitalSignatureImageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Signature_File_NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Signature_File_ContentTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] IDFrontImageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CNIC_F_File_NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CNIC_F_File_ContentTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] IDBackImageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CNIC_B_File_NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CNIC_B_File_ContentTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] ProofOfNRPImageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NRP_File_NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NRP_File_ContentTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] proofOfIncomeImageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProofIncome_File_NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProofIncome_File_ContentTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] ZakatDeclarationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ZakatFileNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ZakatFileContentField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Sessionid {
            get {
                return this.SessionidField;
            }
            set {
                if ((this.SessionidField.Equals(value) != true)) {
                    this.SessionidField = value;
                    this.RaisePropertyChanged("Sessionid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public byte[] DigitalSignatureImage {
            get {
                return this.DigitalSignatureImageField;
            }
            set {
                if ((object.ReferenceEquals(this.DigitalSignatureImageField, value) != true)) {
                    this.DigitalSignatureImageField = value;
                    this.RaisePropertyChanged("DigitalSignatureImage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public string Signature_File_Name {
            get {
                return this.Signature_File_NameField;
            }
            set {
                if ((object.ReferenceEquals(this.Signature_File_NameField, value) != true)) {
                    this.Signature_File_NameField = value;
                    this.RaisePropertyChanged("Signature_File_Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public string Signature_File_ContentType {
            get {
                return this.Signature_File_ContentTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.Signature_File_ContentTypeField, value) != true)) {
                    this.Signature_File_ContentTypeField = value;
                    this.RaisePropertyChanged("Signature_File_ContentType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public byte[] IDFrontImage {
            get {
                return this.IDFrontImageField;
            }
            set {
                if ((object.ReferenceEquals(this.IDFrontImageField, value) != true)) {
                    this.IDFrontImageField = value;
                    this.RaisePropertyChanged("IDFrontImage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public string CNIC_F_File_Name {
            get {
                return this.CNIC_F_File_NameField;
            }
            set {
                if ((object.ReferenceEquals(this.CNIC_F_File_NameField, value) != true)) {
                    this.CNIC_F_File_NameField = value;
                    this.RaisePropertyChanged("CNIC_F_File_Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public string CNIC_F_File_ContentType {
            get {
                return this.CNIC_F_File_ContentTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.CNIC_F_File_ContentTypeField, value) != true)) {
                    this.CNIC_F_File_ContentTypeField = value;
                    this.RaisePropertyChanged("CNIC_F_File_ContentType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
        public byte[] IDBackImage {
            get {
                return this.IDBackImageField;
            }
            set {
                if ((object.ReferenceEquals(this.IDBackImageField, value) != true)) {
                    this.IDBackImageField = value;
                    this.RaisePropertyChanged("IDBackImage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=8)]
        public string CNIC_B_File_Name {
            get {
                return this.CNIC_B_File_NameField;
            }
            set {
                if ((object.ReferenceEquals(this.CNIC_B_File_NameField, value) != true)) {
                    this.CNIC_B_File_NameField = value;
                    this.RaisePropertyChanged("CNIC_B_File_Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=9)]
        public string CNIC_B_File_ContentType {
            get {
                return this.CNIC_B_File_ContentTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.CNIC_B_File_ContentTypeField, value) != true)) {
                    this.CNIC_B_File_ContentTypeField = value;
                    this.RaisePropertyChanged("CNIC_B_File_ContentType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=10)]
        public byte[] ProofOfNRPImage {
            get {
                return this.ProofOfNRPImageField;
            }
            set {
                if ((object.ReferenceEquals(this.ProofOfNRPImageField, value) != true)) {
                    this.ProofOfNRPImageField = value;
                    this.RaisePropertyChanged("ProofOfNRPImage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=11)]
        public string NRP_File_Name {
            get {
                return this.NRP_File_NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NRP_File_NameField, value) != true)) {
                    this.NRP_File_NameField = value;
                    this.RaisePropertyChanged("NRP_File_Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=12)]
        public string NRP_File_ContentType {
            get {
                return this.NRP_File_ContentTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.NRP_File_ContentTypeField, value) != true)) {
                    this.NRP_File_ContentTypeField = value;
                    this.RaisePropertyChanged("NRP_File_ContentType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=13)]
        public byte[] proofOfIncomeImage {
            get {
                return this.proofOfIncomeImageField;
            }
            set {
                if ((object.ReferenceEquals(this.proofOfIncomeImageField, value) != true)) {
                    this.proofOfIncomeImageField = value;
                    this.RaisePropertyChanged("proofOfIncomeImage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=14)]
        public string ProofIncome_File_Name {
            get {
                return this.ProofIncome_File_NameField;
            }
            set {
                if ((object.ReferenceEquals(this.ProofIncome_File_NameField, value) != true)) {
                    this.ProofIncome_File_NameField = value;
                    this.RaisePropertyChanged("ProofIncome_File_Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=15)]
        public string ProofIncome_File_ContentType {
            get {
                return this.ProofIncome_File_ContentTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.ProofIncome_File_ContentTypeField, value) != true)) {
                    this.ProofIncome_File_ContentTypeField = value;
                    this.RaisePropertyChanged("ProofIncome_File_ContentType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=16)]
        public byte[] ZakatDeclaration {
            get {
                return this.ZakatDeclarationField;
            }
            set {
                if ((object.ReferenceEquals(this.ZakatDeclarationField, value) != true)) {
                    this.ZakatDeclarationField = value;
                    this.RaisePropertyChanged("ZakatDeclaration");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=17)]
        public string ZakatFileName {
            get {
                return this.ZakatFileNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ZakatFileNameField, value) != true)) {
                    this.ZakatFileNameField = value;
                    this.RaisePropertyChanged("ZakatFileName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=18)]
        public string ZakatFileContent {
            get {
                return this.ZakatFileContentField;
            }
            set {
                if ((object.ReferenceEquals(this.ZakatFileContentField, value) != true)) {
                    this.ZakatFileContentField = value;
                    this.RaisePropertyChanged("ZakatFileContent");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Response", Namespace="http://schemas.datacontract.org/2004/07/RapidFileService.Contracts")]
    [System.SerializableAttribute()]
    public partial class Response : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string responseCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string responseDescriptionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string responseCode {
            get {
                return this.responseCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.responseCodeField, value) != true)) {
                    this.responseCodeField = value;
                    this.RaisePropertyChanged("responseCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string responseDescription {
            get {
                return this.responseDescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.responseDescriptionField, value) != true)) {
                    this.responseDescriptionField = value;
                    this.RaisePropertyChanged("responseDescription");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IFileManagerService")]
    public interface IFileManagerService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFileManagerService/PostData", ReplyAction="http://tempuri.org/IFileManagerService/PostDataResponse")]
        MalawiAdapter.ServiceReference1.Response PostData(MalawiAdapter.ServiceReference1.Request req);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFileManagerService/PostData", ReplyAction="http://tempuri.org/IFileManagerService/PostDataResponse")]
        System.Threading.Tasks.Task<MalawiAdapter.ServiceReference1.Response> PostDataAsync(MalawiAdapter.ServiceReference1.Request req);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IFileManagerServiceChannel : MalawiAdapter.ServiceReference1.IFileManagerService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FileManagerServiceClient : System.ServiceModel.ClientBase<MalawiAdapter.ServiceReference1.IFileManagerService>, MalawiAdapter.ServiceReference1.IFileManagerService {
        
        public FileManagerServiceClient() {
        }
        
        public FileManagerServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FileManagerServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FileManagerServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FileManagerServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public MalawiAdapter.ServiceReference1.Response PostData(MalawiAdapter.ServiceReference1.Request req) {
            return base.Channel.PostData(req);
        }
        
        public System.Threading.Tasks.Task<MalawiAdapter.ServiceReference1.Response> PostDataAsync(MalawiAdapter.ServiceReference1.Request req) {
            return base.Channel.PostDataAsync(req);
        }
    }
}
