<wsdl:definitions xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns="http://tempuri.org/ATMMSGSet" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:tns="http://tempuri.org/ATMMSGSet" xmlns:xsd="http://www.w3.org/2001/XMLSchema" name="ATMMSGSet" targetNamespace="http://tempuri.org/ATMMSGSet">
	<wsdl:documentation>
		<wsdl:appinfo source="WMQI_APPINFO">
			<MRWSDLAppInfo xmlns="http://tempuri.org/ATMMSGSet" imported="true">
				<generatedXSD location="ATMMSGSetService_InlineSchema1.xsd"/>
				<binding hasEncoding="false" imported="true" name="ATMMSGSetSOAP_HTTP_Binding" originalBindingStyle="document"/>
			</MRWSDLAppInfo>
		</wsdl:appinfo>
	</wsdl:documentation>
	<wsdl:types>
		<xsd:schema xmlns:ibmSchExtn="http://www.ibm.com/schema/extensions" xmlns:mrm="http://tempuri.org/ATMMSGSet" targetNamespace="http://tempuri.org/ATMMSGSet">
			<xsd:include schemaLocation="atm.xsd"/>
		</xsd:schema>
	</wsdl:types>
	<wsdl:message name="Operation1_in">
		<wsdl:part element="ATMReq" name="ATMReq"/>
	</wsdl:message>
	<wsdl:message name="Operation1_out">
		<wsdl:part element="ATMRes" name="ATMRes"/>
	</wsdl:message>
	<wsdl:portType name="ATMMSGSetPortType">
		<wsdl:operation name="Operation1">
			<wsdl:input message="Operation1_in" name="Operation1_Input"/>
			<wsdl:output message="Operation1_out" name="Operation1_Output"/>
		</wsdl:operation>
	</wsdl:portType>
	<wsdl:binding name="ATMMSGSetSOAP_HTTP_Binding" type="ATMMSGSetPortType">
		<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
		<wsdl:operation name="Operation1">
			<soap:operation soapAction=""/>
			<wsdl:input name="Operation1_Input">
				<soap:body parts="ATMReq" use="literal"/>
			</wsdl:input>
			<wsdl:output name="Operation1_Output">
				<soap:body parts="ATMRes" use="literal"/>
			</wsdl:output>
		</wsdl:operation>
	</wsdl:binding>
	<wsdl:service name="ATMMSGSetSOAP_HTTP_Service">
		<wsdl:port binding="ATMMSGSetSOAP_HTTP_Binding" name="ATMMSGSetSOAP_HTTP_Port">
			<soap:address location="http://localhost:7800/ATMMSGSetSOAP_HTTP_Service"/>
		</wsdl:port>
	</wsdl:service>
</wsdl:definitions>