<?xml version="1.0" encoding="UTF-8"?><!--File TitleFetchService.wsdl, application TitleFetchService--><wsdl:definitions xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" name="TitleFetchService" targetNamespace="http://TitleFetchService" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" xmlns:tns="http://TitleFetchService" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <wsdl:documentation>
    <wsdl:appinfo source="WMQI_APPINFO">
      <MRWSDLAppInfo imported="true">
        <binding hasEncoding="false" imported="true" name="TitleFetchServiceHttpBinding" originalBindingStyle="document"/>
        <generatedXSD location="TitleFetchService_InlineSchema1.xsd"/>
      </MRWSDLAppInfo>
    </wsdl:appinfo>
  </wsdl:documentation>
  
  
  <wsdl:types>
    
        <xsd:schema targetNamespace="http://TitleFetchService" xmlns:ibmSchExtn="http://www.ibm.com/schema/extensions">
            <xsd:include schemaLocation="http://172.24.81.152:7800/TitleFetchService?xsd=xsd0"/>
            <xsd:include schemaLocation="http://172.24.81.152:7800/TitleFetchService?xsd=xsd1"/>
            <xsd:include schemaLocation="http://172.24.81.152:7800/TitleFetchService?xsd=xsd2"/>
    </xsd:schema>
    </wsdl:types>
  <wsdl:message name="TitleFetchRequestMsg">
    <wsdl:part element="tns:TitleFetch" name="TitleFetchParameters"/>
  </wsdl:message>
  <wsdl:message name="TitleFetchResponseMsg">
    <wsdl:part element="tns:TitleFetchResponse" name="TitleFetchResult"/>
  </wsdl:message>
  <wsdl:portType name="TitleFetchService">
    <wsdl:operation name="TitleFetch">
      <wsdl:input message="tns:TitleFetchRequestMsg" name="TitleFetchRequest"/>
      <wsdl:output message="tns:TitleFetchResponseMsg" name="TitleFetchResponse"/>
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:binding name="TitleFetchServiceHttpBinding" type="tns:TitleFetchService">
        <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
        <wsdl:operation name="TitleFetch">
      <soap:operation soapAction="http://TitleFetchService/TitleFetch"/>
      <wsdl:input name="TitleFetchRequest">
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output name="TitleFetchResponse">
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
    </wsdl:binding>
  <wsdl:service name="TitleFetchServiceHttpService">
    <wsdl:port binding="tns:TitleFetchServiceHttpBinding" name="TitleFetchServiceHttpPort">
      <soap:address location="http://172.24.81.152:7800/TitleFetchService"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>