//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MalawiAdapter.NADRATranslationService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://NADRAVerificationService", ConfigurationName="NADRATranslationService.NADRAVerificationService")]
    public interface NADRAVerificationService {
        
        // CODEGEN: Generating message contract since the operation VerifyFingerPrint is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://NADRAVerificationService/VerifyFingerPrint", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        MalawiAdapter.NADRATranslationService.VerifyFingerPrintResponse1 VerifyFingerPrint(MalawiAdapter.NADRATranslationService.VerifyFingerPrintRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://NADRAVerificationService/VerifyFingerPrint", ReplyAction="*")]
        System.Threading.Tasks.Task<MalawiAdapter.NADRATranslationService.VerifyFingerPrintResponse1> VerifyFingerPrintAsync(MalawiAdapter.NADRATranslationService.VerifyFingerPrintRequest request);
        
        // CODEGEN: Generating message contract since the operation VerifyCNIC is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://NADRAVerificationService/VerifyCNIC", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        MalawiAdapter.NADRATranslationService.VerifyCNICResponse1 VerifyCNIC(MalawiAdapter.NADRATranslationService.VerifyCNICRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://NADRAVerificationService/VerifyCNIC", ReplyAction="*")]
        System.Threading.Tasks.Task<MalawiAdapter.NADRATranslationService.VerifyCNICResponse1> VerifyCNICAsync(MalawiAdapter.NADRATranslationService.VerifyCNICRequest request);
        
        // CODEGEN: Generating message contract since the operation VerifyFingerPrintOTC is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://NADRAVerificationService/VerifyFingerPrintOTC", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        MalawiAdapter.NADRATranslationService.VerifyFingerPrintOTCResponse1 VerifyFingerPrintOTC(MalawiAdapter.NADRATranslationService.VerifyFingerPrintOTCRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://NADRAVerificationService/VerifyFingerPrintOTC", ReplyAction="*")]
        System.Threading.Tasks.Task<MalawiAdapter.NADRATranslationService.VerifyFingerPrintOTCResponse1> VerifyFingerPrintOTCAsync(MalawiAdapter.NADRATranslationService.VerifyFingerPrintOTCRequest request);
        
        // CODEGEN: Generating message contract since the operation VerifyFingerPrintsMobile is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://NADRAVerificationService/VerifyFingerPrintsMobile", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        MalawiAdapter.NADRATranslationService.VerifyFingerPrintsMobileResponse1 VerifyFingerPrintsMobile(MalawiAdapter.NADRATranslationService.VerifyFingerPrintsMobileRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://NADRAVerificationService/VerifyFingerPrintsMobile", ReplyAction="*")]
        System.Threading.Tasks.Task<MalawiAdapter.NADRATranslationService.VerifyFingerPrintsMobileResponse1> VerifyFingerPrintsMobileAsync(MalawiAdapter.NADRATranslationService.VerifyFingerPrintsMobileRequest request);
        
        // CODEGEN: Generating message contract since the operation VerifyDetails is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://NADRAVerificationService/VerifyDetails", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        MalawiAdapter.NADRATranslationService.VerifyDetailsResponse1 VerifyDetails(MalawiAdapter.NADRATranslationService.VerifyDetailsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://NADRAVerificationService/VerifyDetails", ReplyAction="*")]
        System.Threading.Tasks.Task<MalawiAdapter.NADRATranslationService.VerifyDetailsResponse1> VerifyDetailsAsync(MalawiAdapter.NADRATranslationService.VerifyDetailsRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://NADRAVerificationService")]
    public partial class VerifyFingerPrint : object, System.ComponentModel.INotifyPropertyChanged {
        
        private VerifyFingerPrintRequestType verifyFingerPrintRequestField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public VerifyFingerPrintRequestType VerifyFingerPrintRequest {
            get {
                return this.verifyFingerPrintRequestField;
            }
            set {
                this.verifyFingerPrintRequestField = value;
                this.RaisePropertyChanged("VerifyFingerPrintRequest");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://NADRAVerificationService")]
    public partial class VerifyFingerPrintRequestType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string tRANSACTION_IDField;
        
        private string sESSION_IDField;
        
        private string cITIZEN_NUMBERField;
        
        private string cONTACT_NUMBERField;
        
        private string fINGER_INDEXField;
        
        private string fINGER_TEMPLATEField;
        
        private string tEMPLATE_TYPEField;
        
        private string aREA_NAMEField;
        
        private string aCCOUNT_TYPEField;
        
        private string cHANNEL_IDField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string TRANSACTION_ID {
            get {
                return this.tRANSACTION_IDField;
            }
            set {
                this.tRANSACTION_IDField = value;
                this.RaisePropertyChanged("TRANSACTION_ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string SESSION_ID {
            get {
                return this.sESSION_IDField;
            }
            set {
                this.sESSION_IDField = value;
                this.RaisePropertyChanged("SESSION_ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string CITIZEN_NUMBER {
            get {
                return this.cITIZEN_NUMBERField;
            }
            set {
                this.cITIZEN_NUMBERField = value;
                this.RaisePropertyChanged("CITIZEN_NUMBER");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string CONTACT_NUMBER {
            get {
                return this.cONTACT_NUMBERField;
            }
            set {
                this.cONTACT_NUMBERField = value;
                this.RaisePropertyChanged("CONTACT_NUMBER");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string FINGER_INDEX {
            get {
                return this.fINGER_INDEXField;
            }
            set {
                this.fINGER_INDEXField = value;
                this.RaisePropertyChanged("FINGER_INDEX");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string FINGER_TEMPLATE {
            get {
                return this.fINGER_TEMPLATEField;
            }
            set {
                this.fINGER_TEMPLATEField = value;
                this.RaisePropertyChanged("FINGER_TEMPLATE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string TEMPLATE_TYPE {
            get {
                return this.tEMPLATE_TYPEField;
            }
            set {
                this.tEMPLATE_TYPEField = value;
                this.RaisePropertyChanged("TEMPLATE_TYPE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string AREA_NAME {
            get {
                return this.aREA_NAMEField;
            }
            set {
                this.aREA_NAMEField = value;
                this.RaisePropertyChanged("AREA_NAME");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string ACCOUNT_TYPE {
            get {
                return this.aCCOUNT_TYPEField;
            }
            set {
                this.aCCOUNT_TYPEField = value;
                this.RaisePropertyChanged("ACCOUNT_TYPE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string CHANNEL_ID {
            get {
                return this.cHANNEL_IDField;
            }
            set {
                this.cHANNEL_IDField = value;
                this.RaisePropertyChanged("CHANNEL_ID");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://NADRAVerificationService")]
    public partial class VerifyDetailsResultType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string responseCodeField;
        
        private string responseDescriptionField;
        
        private string dataField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string ResponseCode {
            get {
                return this.responseCodeField;
            }
            set {
                this.responseCodeField = value;
                this.RaisePropertyChanged("ResponseCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string ResponseDescription {
            get {
                return this.responseDescriptionField;
            }
            set {
                this.responseDescriptionField = value;
                this.RaisePropertyChanged("ResponseDescription");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string Data {
            get {
                return this.dataField;
            }
            set {
                this.dataField = value;
                this.RaisePropertyChanged("Data");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://NADRAVerificationService")]
    public partial class VerifyDetailsInputRequestType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string cITIZEN_NUMBERField;
        
        private string cONTACT_NUMBERField;
        
        private string aREA_NAMEField;
        
        private string fINGER_INDEXField;
        
        private string fINGER_TEMPLATEField;
        
        private string tEMPLATE_TYPEField;
        
        private string rEMITTANCE_AMOUNTField;
        
        private string rEMITTANCE_TYPEField;
        
        private string sECONDARY_CITIZEN_NUMBERField;
        
        private string sECONDARY_CONTACT_NUMBERField;
        
        private string aCCOUNT_NUMBERField;
        
        private string aCCOUNT_TYPEField;
        
        private string cHANNEL_IDField;
        
        private bool pHOTOGRAPH_REQUIREDField;
        
        private bool oTCField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string CITIZEN_NUMBER {
            get {
                return this.cITIZEN_NUMBERField;
            }
            set {
                this.cITIZEN_NUMBERField = value;
                this.RaisePropertyChanged("CITIZEN_NUMBER");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string CONTACT_NUMBER {
            get {
                return this.cONTACT_NUMBERField;
            }
            set {
                this.cONTACT_NUMBERField = value;
                this.RaisePropertyChanged("CONTACT_NUMBER");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string AREA_NAME {
            get {
                return this.aREA_NAMEField;
            }
            set {
                this.aREA_NAMEField = value;
                this.RaisePropertyChanged("AREA_NAME");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string FINGER_INDEX {
            get {
                return this.fINGER_INDEXField;
            }
            set {
                this.fINGER_INDEXField = value;
                this.RaisePropertyChanged("FINGER_INDEX");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string FINGER_TEMPLATE {
            get {
                return this.fINGER_TEMPLATEField;
            }
            set {
                this.fINGER_TEMPLATEField = value;
                this.RaisePropertyChanged("FINGER_TEMPLATE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string TEMPLATE_TYPE {
            get {
                return this.tEMPLATE_TYPEField;
            }
            set {
                this.tEMPLATE_TYPEField = value;
                this.RaisePropertyChanged("TEMPLATE_TYPE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string REMITTANCE_AMOUNT {
            get {
                return this.rEMITTANCE_AMOUNTField;
            }
            set {
                this.rEMITTANCE_AMOUNTField = value;
                this.RaisePropertyChanged("REMITTANCE_AMOUNT");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string REMITTANCE_TYPE {
            get {
                return this.rEMITTANCE_TYPEField;
            }
            set {
                this.rEMITTANCE_TYPEField = value;
                this.RaisePropertyChanged("REMITTANCE_TYPE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string SECONDARY_CITIZEN_NUMBER {
            get {
                return this.sECONDARY_CITIZEN_NUMBERField;
            }
            set {
                this.sECONDARY_CITIZEN_NUMBERField = value;
                this.RaisePropertyChanged("SECONDARY_CITIZEN_NUMBER");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string SECONDARY_CONTACT_NUMBER {
            get {
                return this.sECONDARY_CONTACT_NUMBERField;
            }
            set {
                this.sECONDARY_CONTACT_NUMBERField = value;
                this.RaisePropertyChanged("SECONDARY_CONTACT_NUMBER");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string ACCOUNT_NUMBER {
            get {
                return this.aCCOUNT_NUMBERField;
            }
            set {
                this.aCCOUNT_NUMBERField = value;
                this.RaisePropertyChanged("ACCOUNT_NUMBER");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public string ACCOUNT_TYPE {
            get {
                return this.aCCOUNT_TYPEField;
            }
            set {
                this.aCCOUNT_TYPEField = value;
                this.RaisePropertyChanged("ACCOUNT_TYPE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public string CHANNEL_ID {
            get {
                return this.cHANNEL_IDField;
            }
            set {
                this.cHANNEL_IDField = value;
                this.RaisePropertyChanged("CHANNEL_ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
        public bool PHOTOGRAPH_REQUIRED {
            get {
                return this.pHOTOGRAPH_REQUIREDField;
            }
            set {
                this.pHOTOGRAPH_REQUIREDField = value;
                this.RaisePropertyChanged("PHOTOGRAPH_REQUIRED");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=14)]
        public bool OTC {
            get {
                return this.oTCField;
            }
            set {
                this.oTCField = value;
                this.RaisePropertyChanged("OTC");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://NADRAVerificationService")]
    public partial class VerifyFingerPrintMobileInputRquestType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string tRANSACTION_IDField;
        
        private string sESSION_IDField;
        
        private string cITIZEN_NUMBERField;
        
        private string cONTACT_NUMBERField;
        
        private string fINGER_INDEXField;
        
        private string fINGER_TEMPLATEField;
        
        private string tEMPLATE_TYPEField;
        
        private string aREA_NAMEField;
        
        private string cHANNEL_IDField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string TRANSACTION_ID {
            get {
                return this.tRANSACTION_IDField;
            }
            set {
                this.tRANSACTION_IDField = value;
                this.RaisePropertyChanged("TRANSACTION_ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string SESSION_ID {
            get {
                return this.sESSION_IDField;
            }
            set {
                this.sESSION_IDField = value;
                this.RaisePropertyChanged("SESSION_ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string CITIZEN_NUMBER {
            get {
                return this.cITIZEN_NUMBERField;
            }
            set {
                this.cITIZEN_NUMBERField = value;
                this.RaisePropertyChanged("CITIZEN_NUMBER");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string CONTACT_NUMBER {
            get {
                return this.cONTACT_NUMBERField;
            }
            set {
                this.cONTACT_NUMBERField = value;
                this.RaisePropertyChanged("CONTACT_NUMBER");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string FINGER_INDEX {
            get {
                return this.fINGER_INDEXField;
            }
            set {
                this.fINGER_INDEXField = value;
                this.RaisePropertyChanged("FINGER_INDEX");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string FINGER_TEMPLATE {
            get {
                return this.fINGER_TEMPLATEField;
            }
            set {
                this.fINGER_TEMPLATEField = value;
                this.RaisePropertyChanged("FINGER_TEMPLATE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string TEMPLATE_TYPE {
            get {
                return this.tEMPLATE_TYPEField;
            }
            set {
                this.tEMPLATE_TYPEField = value;
                this.RaisePropertyChanged("TEMPLATE_TYPE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string AREA_NAME {
            get {
                return this.aREA_NAMEField;
            }
            set {
                this.aREA_NAMEField = value;
                this.RaisePropertyChanged("AREA_NAME");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string CHANNEL_ID {
            get {
                return this.cHANNEL_IDField;
            }
            set {
                this.cHANNEL_IDField = value;
                this.RaisePropertyChanged("CHANNEL_ID");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://NADRAVerificationService")]
    public partial class VerifyFingerPrintOTCInputRequestType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string tRANSACTION_IDField;
        
        private string sESSION_IDField;
        
        private string pRIMARY_CITIZEN_NUMBERField;
        
        private string pRIMARY_CONTACT_NUMBERField;
        
        private string fINGER_INDEXField;
        
        private string fINGER_TEMPLATEField;
        
        private string tEMPLATE_TYPEField;
        
        private string rEMITTANCE_AMOUNTField;
        
        private string rEMITTANCE_TYPEField;
        
        private string sECONDARY_CITIZEN_NUMBERField;
        
        private string sECONDARY_CONTACT_NUMBERField;
        
        private string aREA_NAMEField;
        
        private string aCCOUNT_NUMBERField;
        
        private string cHANNEL_IDField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string TRANSACTION_ID {
            get {
                return this.tRANSACTION_IDField;
            }
            set {
                this.tRANSACTION_IDField = value;
                this.RaisePropertyChanged("TRANSACTION_ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string SESSION_ID {
            get {
                return this.sESSION_IDField;
            }
            set {
                this.sESSION_IDField = value;
                this.RaisePropertyChanged("SESSION_ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string PRIMARY_CITIZEN_NUMBER {
            get {
                return this.pRIMARY_CITIZEN_NUMBERField;
            }
            set {
                this.pRIMARY_CITIZEN_NUMBERField = value;
                this.RaisePropertyChanged("PRIMARY_CITIZEN_NUMBER");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string PRIMARY_CONTACT_NUMBER {
            get {
                return this.pRIMARY_CONTACT_NUMBERField;
            }
            set {
                this.pRIMARY_CONTACT_NUMBERField = value;
                this.RaisePropertyChanged("PRIMARY_CONTACT_NUMBER");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string FINGER_INDEX {
            get {
                return this.fINGER_INDEXField;
            }
            set {
                this.fINGER_INDEXField = value;
                this.RaisePropertyChanged("FINGER_INDEX");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string FINGER_TEMPLATE {
            get {
                return this.fINGER_TEMPLATEField;
            }
            set {
                this.fINGER_TEMPLATEField = value;
                this.RaisePropertyChanged("FINGER_TEMPLATE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string TEMPLATE_TYPE {
            get {
                return this.tEMPLATE_TYPEField;
            }
            set {
                this.tEMPLATE_TYPEField = value;
                this.RaisePropertyChanged("TEMPLATE_TYPE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string REMITTANCE_AMOUNT {
            get {
                return this.rEMITTANCE_AMOUNTField;
            }
            set {
                this.rEMITTANCE_AMOUNTField = value;
                this.RaisePropertyChanged("REMITTANCE_AMOUNT");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string REMITTANCE_TYPE {
            get {
                return this.rEMITTANCE_TYPEField;
            }
            set {
                this.rEMITTANCE_TYPEField = value;
                this.RaisePropertyChanged("REMITTANCE_TYPE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string SECONDARY_CITIZEN_NUMBER {
            get {
                return this.sECONDARY_CITIZEN_NUMBERField;
            }
            set {
                this.sECONDARY_CITIZEN_NUMBERField = value;
                this.RaisePropertyChanged("SECONDARY_CITIZEN_NUMBER");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string SECONDARY_CONTACT_NUMBER {
            get {
                return this.sECONDARY_CONTACT_NUMBERField;
            }
            set {
                this.sECONDARY_CONTACT_NUMBERField = value;
                this.RaisePropertyChanged("SECONDARY_CONTACT_NUMBER");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public string AREA_NAME {
            get {
                return this.aREA_NAMEField;
            }
            set {
                this.aREA_NAMEField = value;
                this.RaisePropertyChanged("AREA_NAME");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public string ACCOUNT_NUMBER {
            get {
                return this.aCCOUNT_NUMBERField;
            }
            set {
                this.aCCOUNT_NUMBERField = value;
                this.RaisePropertyChanged("ACCOUNT_NUMBER");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
        public string CHANNEL_ID {
            get {
                return this.cHANNEL_IDField;
            }
            set {
                this.cHANNEL_IDField = value;
                this.RaisePropertyChanged("CHANNEL_ID");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://NADRAVerificationService")]
    public partial class VerifyCNICResultType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string responseCodeField;
        
        private string responseDescriptionField;
        
        private string dataField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string ResponseCode {
            get {
                return this.responseCodeField;
            }
            set {
                this.responseCodeField = value;
                this.RaisePropertyChanged("ResponseCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string ResponseDescription {
            get {
                return this.responseDescriptionField;
            }
            set {
                this.responseDescriptionField = value;
                this.RaisePropertyChanged("ResponseDescription");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string Data {
            get {
                return this.dataField;
            }
            set {
                this.dataField = value;
                this.RaisePropertyChanged("Data");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://NADRAVerificationService")]
    public partial class VerifyCNICInputRequestType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string tRANSACTION_IDField;
        
        private string sESSION_IDField;
        
        private string cITIZEN_NUMBERField;
        
        private string iSSUE_DATEField;
        
        private string cONTACT_NUMBERField;
        
        private string aREA_NAMEField;
        
        private string cHANNEL_IDField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string TRANSACTION_ID {
            get {
                return this.tRANSACTION_IDField;
            }
            set {
                this.tRANSACTION_IDField = value;
                this.RaisePropertyChanged("TRANSACTION_ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string SESSION_ID {
            get {
                return this.sESSION_IDField;
            }
            set {
                this.sESSION_IDField = value;
                this.RaisePropertyChanged("SESSION_ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string CITIZEN_NUMBER {
            get {
                return this.cITIZEN_NUMBERField;
            }
            set {
                this.cITIZEN_NUMBERField = value;
                this.RaisePropertyChanged("CITIZEN_NUMBER");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string ISSUE_DATE {
            get {
                return this.iSSUE_DATEField;
            }
            set {
                this.iSSUE_DATEField = value;
                this.RaisePropertyChanged("ISSUE_DATE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string CONTACT_NUMBER {
            get {
                return this.cONTACT_NUMBERField;
            }
            set {
                this.cONTACT_NUMBERField = value;
                this.RaisePropertyChanged("CONTACT_NUMBER");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string AREA_NAME {
            get {
                return this.aREA_NAMEField;
            }
            set {
                this.aREA_NAMEField = value;
                this.RaisePropertyChanged("AREA_NAME");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string CHANNEL_ID {
            get {
                return this.cHANNEL_IDField;
            }
            set {
                this.cHANNEL_IDField = value;
                this.RaisePropertyChanged("CHANNEL_ID");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://NADRAVerificationService")]
    public partial class VerifyFingerPrintResultType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string responseCodeField;
        
        private string responseDescriptionField;
        
        private string dataField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string ResponseCode {
            get {
                return this.responseCodeField;
            }
            set {
                this.responseCodeField = value;
                this.RaisePropertyChanged("ResponseCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string ResponseDescription {
            get {
                return this.responseDescriptionField;
            }
            set {
                this.responseDescriptionField = value;
                this.RaisePropertyChanged("ResponseDescription");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string Data {
            get {
                return this.dataField;
            }
            set {
                this.dataField = value;
                this.RaisePropertyChanged("Data");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://NADRAVerificationService")]
    public partial class VerifyFingerPrintResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private VerifyFingerPrintResultType verifyFingerPrintResultField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public VerifyFingerPrintResultType VerifyFingerPrintResult {
            get {
                return this.verifyFingerPrintResultField;
            }
            set {
                this.verifyFingerPrintResultField = value;
                this.RaisePropertyChanged("VerifyFingerPrintResult");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class VerifyFingerPrintRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://NADRAVerificationService", Order=0)]
        public MalawiAdapter.NADRATranslationService.VerifyFingerPrint VerifyFingerPrint;
        
        public VerifyFingerPrintRequest() {
        }
        
        public VerifyFingerPrintRequest(MalawiAdapter.NADRATranslationService.VerifyFingerPrint VerifyFingerPrint) {
            this.VerifyFingerPrint = VerifyFingerPrint;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class VerifyFingerPrintResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://NADRAVerificationService", Order=0)]
        public MalawiAdapter.NADRATranslationService.VerifyFingerPrintResponse VerifyFingerPrintResponse;
        
        public VerifyFingerPrintResponse1() {
        }
        
        public VerifyFingerPrintResponse1(MalawiAdapter.NADRATranslationService.VerifyFingerPrintResponse VerifyFingerPrintResponse) {
            this.VerifyFingerPrintResponse = VerifyFingerPrintResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://NADRAVerificationService")]
    public partial class VerifyCNIC : object, System.ComponentModel.INotifyPropertyChanged {
        
        private VerifyCNICInputRequestType verifyCNICInputRequestField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public VerifyCNICInputRequestType VerifyCNICInputRequest {
            get {
                return this.verifyCNICInputRequestField;
            }
            set {
                this.verifyCNICInputRequestField = value;
                this.RaisePropertyChanged("VerifyCNICInputRequest");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://NADRAVerificationService")]
    public partial class VerifyCNICResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private VerifyCNICResultType verifyCNICResultField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public VerifyCNICResultType VerifyCNICResult {
            get {
                return this.verifyCNICResultField;
            }
            set {
                this.verifyCNICResultField = value;
                this.RaisePropertyChanged("VerifyCNICResult");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class VerifyCNICRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://NADRAVerificationService", Order=0)]
        public MalawiAdapter.NADRATranslationService.VerifyCNIC VerifyCNIC;
        
        public VerifyCNICRequest() {
        }
        
        public VerifyCNICRequest(MalawiAdapter.NADRATranslationService.VerifyCNIC VerifyCNIC) {
            this.VerifyCNIC = VerifyCNIC;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class VerifyCNICResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://NADRAVerificationService", Order=0)]
        public MalawiAdapter.NADRATranslationService.VerifyCNICResponse VerifyCNICResponse;
        
        public VerifyCNICResponse1() {
        }
        
        public VerifyCNICResponse1(MalawiAdapter.NADRATranslationService.VerifyCNICResponse VerifyCNICResponse) {
            this.VerifyCNICResponse = VerifyCNICResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://NADRAVerificationService")]
    public partial class VerifyFingerPrintOTC : object, System.ComponentModel.INotifyPropertyChanged {
        
        private VerifyFingerPrintOTCInputRequestType verifyFingerPrintOTCInputRequestField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public VerifyFingerPrintOTCInputRequestType VerifyFingerPrintOTCInputRequest {
            get {
                return this.verifyFingerPrintOTCInputRequestField;
            }
            set {
                this.verifyFingerPrintOTCInputRequestField = value;
                this.RaisePropertyChanged("VerifyFingerPrintOTCInputRequest");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://NADRAVerificationService")]
    public partial class VerifyFingerPrintOTCResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private VerifyCNICResultType verifyFingerPrintOTCResultField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public VerifyCNICResultType VerifyFingerPrintOTCResult {
            get {
                return this.verifyFingerPrintOTCResultField;
            }
            set {
                this.verifyFingerPrintOTCResultField = value;
                this.RaisePropertyChanged("VerifyFingerPrintOTCResult");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class VerifyFingerPrintOTCRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://NADRAVerificationService", Order=0)]
        public MalawiAdapter.NADRATranslationService.VerifyFingerPrintOTC VerifyFingerPrintOTC;
        
        public VerifyFingerPrintOTCRequest() {
        }
        
        public VerifyFingerPrintOTCRequest(MalawiAdapter.NADRATranslationService.VerifyFingerPrintOTC VerifyFingerPrintOTC) {
            this.VerifyFingerPrintOTC = VerifyFingerPrintOTC;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class VerifyFingerPrintOTCResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://NADRAVerificationService", Order=0)]
        public MalawiAdapter.NADRATranslationService.VerifyFingerPrintOTCResponse VerifyFingerPrintOTCResponse;
        
        public VerifyFingerPrintOTCResponse1() {
        }
        
        public VerifyFingerPrintOTCResponse1(MalawiAdapter.NADRATranslationService.VerifyFingerPrintOTCResponse VerifyFingerPrintOTCResponse) {
            this.VerifyFingerPrintOTCResponse = VerifyFingerPrintOTCResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://NADRAVerificationService")]
    public partial class VerifyFingerPrintsMobile : object, System.ComponentModel.INotifyPropertyChanged {
        
        private VerifyFingerPrintMobileInputRquestType verifyFingerPrintMobileInputRquestField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public VerifyFingerPrintMobileInputRquestType VerifyFingerPrintMobileInputRquest {
            get {
                return this.verifyFingerPrintMobileInputRquestField;
            }
            set {
                this.verifyFingerPrintMobileInputRquestField = value;
                this.RaisePropertyChanged("VerifyFingerPrintMobileInputRquest");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://NADRAVerificationService")]
    public partial class VerifyFingerPrintsMobileResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private VerifyFingerPrintResultType verifyFingerPrintResultField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public VerifyFingerPrintResultType VerifyFingerPrintResult {
            get {
                return this.verifyFingerPrintResultField;
            }
            set {
                this.verifyFingerPrintResultField = value;
                this.RaisePropertyChanged("VerifyFingerPrintResult");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class VerifyFingerPrintsMobileRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://NADRAVerificationService", Order=0)]
        public MalawiAdapter.NADRATranslationService.VerifyFingerPrintsMobile VerifyFingerPrintsMobile;
        
        public VerifyFingerPrintsMobileRequest() {
        }
        
        public VerifyFingerPrintsMobileRequest(MalawiAdapter.NADRATranslationService.VerifyFingerPrintsMobile VerifyFingerPrintsMobile) {
            this.VerifyFingerPrintsMobile = VerifyFingerPrintsMobile;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class VerifyFingerPrintsMobileResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://NADRAVerificationService", Order=0)]
        public MalawiAdapter.NADRATranslationService.VerifyFingerPrintsMobileResponse VerifyFingerPrintsMobileResponse;
        
        public VerifyFingerPrintsMobileResponse1() {
        }
        
        public VerifyFingerPrintsMobileResponse1(MalawiAdapter.NADRATranslationService.VerifyFingerPrintsMobileResponse VerifyFingerPrintsMobileResponse) {
            this.VerifyFingerPrintsMobileResponse = VerifyFingerPrintsMobileResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://NADRAVerificationService")]
    public partial class VerifyDetails : object, System.ComponentModel.INotifyPropertyChanged {
        
        private VerifyDetailsInputRequestType verifyDetailsInputRequestField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public VerifyDetailsInputRequestType VerifyDetailsInputRequest {
            get {
                return this.verifyDetailsInputRequestField;
            }
            set {
                this.verifyDetailsInputRequestField = value;
                this.RaisePropertyChanged("VerifyDetailsInputRequest");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://NADRAVerificationService")]
    public partial class VerifyDetailsResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private VerifyDetailsResultType verifyDetailsResultField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public VerifyDetailsResultType VerifyDetailsResult {
            get {
                return this.verifyDetailsResultField;
            }
            set {
                this.verifyDetailsResultField = value;
                this.RaisePropertyChanged("VerifyDetailsResult");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class VerifyDetailsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://NADRAVerificationService", Order=0)]
        public MalawiAdapter.NADRATranslationService.VerifyDetails VerifyDetails;
        
        public VerifyDetailsRequest() {
        }
        
        public VerifyDetailsRequest(MalawiAdapter.NADRATranslationService.VerifyDetails VerifyDetails) {
            this.VerifyDetails = VerifyDetails;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class VerifyDetailsResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://NADRAVerificationService", Order=0)]
        public MalawiAdapter.NADRATranslationService.VerifyDetailsResponse VerifyDetailsResponse;
        
        public VerifyDetailsResponse1() {
        }
        
        public VerifyDetailsResponse1(MalawiAdapter.NADRATranslationService.VerifyDetailsResponse VerifyDetailsResponse) {
            this.VerifyDetailsResponse = VerifyDetailsResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface NADRAVerificationServiceChannel : MalawiAdapter.NADRATranslationService.NADRAVerificationService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class NADRAVerificationServiceClient : System.ServiceModel.ClientBase<MalawiAdapter.NADRATranslationService.NADRAVerificationService>, MalawiAdapter.NADRATranslationService.NADRAVerificationService {
        
        public NADRAVerificationServiceClient() {
        }
        
        public NADRAVerificationServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public NADRAVerificationServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NADRAVerificationServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NADRAVerificationServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MalawiAdapter.NADRATranslationService.VerifyFingerPrintResponse1 MalawiAdapter.NADRATranslationService.NADRAVerificationService.VerifyFingerPrint(MalawiAdapter.NADRATranslationService.VerifyFingerPrintRequest request) {
            return base.Channel.VerifyFingerPrint(request);
        }
        
        public MalawiAdapter.NADRATranslationService.VerifyFingerPrintResponse VerifyFingerPrint(MalawiAdapter.NADRATranslationService.VerifyFingerPrint VerifyFingerPrint1) {
            MalawiAdapter.NADRATranslationService.VerifyFingerPrintRequest inValue = new MalawiAdapter.NADRATranslationService.VerifyFingerPrintRequest();
            inValue.VerifyFingerPrint = VerifyFingerPrint1;
            MalawiAdapter.NADRATranslationService.VerifyFingerPrintResponse1 retVal = ((MalawiAdapter.NADRATranslationService.NADRAVerificationService)(this)).VerifyFingerPrint(inValue);
            return retVal.VerifyFingerPrintResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MalawiAdapter.NADRATranslationService.VerifyFingerPrintResponse1> MalawiAdapter.NADRATranslationService.NADRAVerificationService.VerifyFingerPrintAsync(MalawiAdapter.NADRATranslationService.VerifyFingerPrintRequest request) {
            return base.Channel.VerifyFingerPrintAsync(request);
        }
        
        public System.Threading.Tasks.Task<MalawiAdapter.NADRATranslationService.VerifyFingerPrintResponse1> VerifyFingerPrintAsync(MalawiAdapter.NADRATranslationService.VerifyFingerPrint VerifyFingerPrint) {
            MalawiAdapter.NADRATranslationService.VerifyFingerPrintRequest inValue = new MalawiAdapter.NADRATranslationService.VerifyFingerPrintRequest();
            inValue.VerifyFingerPrint = VerifyFingerPrint;
            return ((MalawiAdapter.NADRATranslationService.NADRAVerificationService)(this)).VerifyFingerPrintAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MalawiAdapter.NADRATranslationService.VerifyCNICResponse1 MalawiAdapter.NADRATranslationService.NADRAVerificationService.VerifyCNIC(MalawiAdapter.NADRATranslationService.VerifyCNICRequest request) {
            return base.Channel.VerifyCNIC(request);
        }
        
        public MalawiAdapter.NADRATranslationService.VerifyCNICResponse VerifyCNIC(MalawiAdapter.NADRATranslationService.VerifyCNIC VerifyCNIC1) {
            MalawiAdapter.NADRATranslationService.VerifyCNICRequest inValue = new MalawiAdapter.NADRATranslationService.VerifyCNICRequest();
            inValue.VerifyCNIC = VerifyCNIC1;
            MalawiAdapter.NADRATranslationService.VerifyCNICResponse1 retVal = ((MalawiAdapter.NADRATranslationService.NADRAVerificationService)(this)).VerifyCNIC(inValue);
            return retVal.VerifyCNICResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MalawiAdapter.NADRATranslationService.VerifyCNICResponse1> MalawiAdapter.NADRATranslationService.NADRAVerificationService.VerifyCNICAsync(MalawiAdapter.NADRATranslationService.VerifyCNICRequest request) {
            return base.Channel.VerifyCNICAsync(request);
        }
        
        public System.Threading.Tasks.Task<MalawiAdapter.NADRATranslationService.VerifyCNICResponse1> VerifyCNICAsync(MalawiAdapter.NADRATranslationService.VerifyCNIC VerifyCNIC) {
            MalawiAdapter.NADRATranslationService.VerifyCNICRequest inValue = new MalawiAdapter.NADRATranslationService.VerifyCNICRequest();
            inValue.VerifyCNIC = VerifyCNIC;
            return ((MalawiAdapter.NADRATranslationService.NADRAVerificationService)(this)).VerifyCNICAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MalawiAdapter.NADRATranslationService.VerifyFingerPrintOTCResponse1 MalawiAdapter.NADRATranslationService.NADRAVerificationService.VerifyFingerPrintOTC(MalawiAdapter.NADRATranslationService.VerifyFingerPrintOTCRequest request) {
            return base.Channel.VerifyFingerPrintOTC(request);
        }
        
        public MalawiAdapter.NADRATranslationService.VerifyFingerPrintOTCResponse VerifyFingerPrintOTC(MalawiAdapter.NADRATranslationService.VerifyFingerPrintOTC VerifyFingerPrintOTC1) {
            MalawiAdapter.NADRATranslationService.VerifyFingerPrintOTCRequest inValue = new MalawiAdapter.NADRATranslationService.VerifyFingerPrintOTCRequest();
            inValue.VerifyFingerPrintOTC = VerifyFingerPrintOTC1;
            MalawiAdapter.NADRATranslationService.VerifyFingerPrintOTCResponse1 retVal = ((MalawiAdapter.NADRATranslationService.NADRAVerificationService)(this)).VerifyFingerPrintOTC(inValue);
            return retVal.VerifyFingerPrintOTCResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MalawiAdapter.NADRATranslationService.VerifyFingerPrintOTCResponse1> MalawiAdapter.NADRATranslationService.NADRAVerificationService.VerifyFingerPrintOTCAsync(MalawiAdapter.NADRATranslationService.VerifyFingerPrintOTCRequest request) {
            return base.Channel.VerifyFingerPrintOTCAsync(request);
        }
        
        public System.Threading.Tasks.Task<MalawiAdapter.NADRATranslationService.VerifyFingerPrintOTCResponse1> VerifyFingerPrintOTCAsync(MalawiAdapter.NADRATranslationService.VerifyFingerPrintOTC VerifyFingerPrintOTC) {
            MalawiAdapter.NADRATranslationService.VerifyFingerPrintOTCRequest inValue = new MalawiAdapter.NADRATranslationService.VerifyFingerPrintOTCRequest();
            inValue.VerifyFingerPrintOTC = VerifyFingerPrintOTC;
            return ((MalawiAdapter.NADRATranslationService.NADRAVerificationService)(this)).VerifyFingerPrintOTCAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MalawiAdapter.NADRATranslationService.VerifyFingerPrintsMobileResponse1 MalawiAdapter.NADRATranslationService.NADRAVerificationService.VerifyFingerPrintsMobile(MalawiAdapter.NADRATranslationService.VerifyFingerPrintsMobileRequest request) {
            return base.Channel.VerifyFingerPrintsMobile(request);
        }
        
        public MalawiAdapter.NADRATranslationService.VerifyFingerPrintsMobileResponse VerifyFingerPrintsMobile(MalawiAdapter.NADRATranslationService.VerifyFingerPrintsMobile VerifyFingerPrintsMobile1) {
            MalawiAdapter.NADRATranslationService.VerifyFingerPrintsMobileRequest inValue = new MalawiAdapter.NADRATranslationService.VerifyFingerPrintsMobileRequest();
            inValue.VerifyFingerPrintsMobile = VerifyFingerPrintsMobile1;
            MalawiAdapter.NADRATranslationService.VerifyFingerPrintsMobileResponse1 retVal = ((MalawiAdapter.NADRATranslationService.NADRAVerificationService)(this)).VerifyFingerPrintsMobile(inValue);
            return retVal.VerifyFingerPrintsMobileResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MalawiAdapter.NADRATranslationService.VerifyFingerPrintsMobileResponse1> MalawiAdapter.NADRATranslationService.NADRAVerificationService.VerifyFingerPrintsMobileAsync(MalawiAdapter.NADRATranslationService.VerifyFingerPrintsMobileRequest request) {
            return base.Channel.VerifyFingerPrintsMobileAsync(request);
        }
        
        public System.Threading.Tasks.Task<MalawiAdapter.NADRATranslationService.VerifyFingerPrintsMobileResponse1> VerifyFingerPrintsMobileAsync(MalawiAdapter.NADRATranslationService.VerifyFingerPrintsMobile VerifyFingerPrintsMobile) {
            MalawiAdapter.NADRATranslationService.VerifyFingerPrintsMobileRequest inValue = new MalawiAdapter.NADRATranslationService.VerifyFingerPrintsMobileRequest();
            inValue.VerifyFingerPrintsMobile = VerifyFingerPrintsMobile;
            return ((MalawiAdapter.NADRATranslationService.NADRAVerificationService)(this)).VerifyFingerPrintsMobileAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MalawiAdapter.NADRATranslationService.VerifyDetailsResponse1 MalawiAdapter.NADRATranslationService.NADRAVerificationService.VerifyDetails(MalawiAdapter.NADRATranslationService.VerifyDetailsRequest request) {
            return base.Channel.VerifyDetails(request);
        }
        
        public MalawiAdapter.NADRATranslationService.VerifyDetailsResponse VerifyDetails(MalawiAdapter.NADRATranslationService.VerifyDetails VerifyDetails1) {
            MalawiAdapter.NADRATranslationService.VerifyDetailsRequest inValue = new MalawiAdapter.NADRATranslationService.VerifyDetailsRequest();
            inValue.VerifyDetails = VerifyDetails1;
            MalawiAdapter.NADRATranslationService.VerifyDetailsResponse1 retVal = ((MalawiAdapter.NADRATranslationService.NADRAVerificationService)(this)).VerifyDetails(inValue);
            return retVal.VerifyDetailsResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MalawiAdapter.NADRATranslationService.VerifyDetailsResponse1> MalawiAdapter.NADRATranslationService.NADRAVerificationService.VerifyDetailsAsync(MalawiAdapter.NADRATranslationService.VerifyDetailsRequest request) {
            return base.Channel.VerifyDetailsAsync(request);
        }
        
        public System.Threading.Tasks.Task<MalawiAdapter.NADRATranslationService.VerifyDetailsResponse1> VerifyDetailsAsync(MalawiAdapter.NADRATranslationService.VerifyDetails VerifyDetails) {
            MalawiAdapter.NADRATranslationService.VerifyDetailsRequest inValue = new MalawiAdapter.NADRATranslationService.VerifyDetailsRequest();
            inValue.VerifyDetails = VerifyDetails;
            return ((MalawiAdapter.NADRATranslationService.NADRAVerificationService)(this)).VerifyDetailsAsync(inValue);
        }
    }
}
