//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MalawiAdapter.TitleFetchService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://TitleFetchService", ConfigurationName="TitleFetchService.TitleFetchService")]
    public interface TitleFetchService {
        
        // CODEGEN: Generating message contract since the operation TitleFetch is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://TitleFetchService/TitleFetch", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        MalawiAdapter.TitleFetchService.TitleFetchResponse1 TitleFetch(MalawiAdapter.TitleFetchService.TitleFetchRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://TitleFetchService/TitleFetch", ReplyAction="*")]
        System.Threading.Tasks.Task<MalawiAdapter.TitleFetchService.TitleFetchResponse1> TitleFetchAsync(MalawiAdapter.TitleFetchService.TitleFetchRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://TitleFetchService")]
    public partial class TitleFetch : object, System.ComponentModel.INotifyPropertyChanged {
        
        private TitleFetchRequestType titleFetchRequestField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public TitleFetchRequestType TitleFetchRequest {
            get {
                return this.titleFetchRequestField;
            }
            set {
                this.titleFetchRequestField = value;
                this.RaisePropertyChanged("TitleFetchRequest");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://TitleFetchService")]
    public partial class TitleFetchRequestType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string channelIDField;
        
        private string deliveryChannelTypeField;
        
        private string customerIDField;
        
        private string channelSpecificDataFieldField;
        
        private string accountBankIMDField;
        
        private string accountNumberField;
        
        private string accountTypeField;
        
        private string accountCurrencyField;
        
        private string iBANField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string ChannelID {
            get {
                return this.channelIDField;
            }
            set {
                this.channelIDField = value;
                this.RaisePropertyChanged("ChannelID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string DeliveryChannelType {
            get {
                return this.deliveryChannelTypeField;
            }
            set {
                this.deliveryChannelTypeField = value;
                this.RaisePropertyChanged("DeliveryChannelType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string CustomerID {
            get {
                return this.customerIDField;
            }
            set {
                this.customerIDField = value;
                this.RaisePropertyChanged("CustomerID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string channelSpecificDataField {
            get {
                return this.channelSpecificDataFieldField;
            }
            set {
                this.channelSpecificDataFieldField = value;
                this.RaisePropertyChanged("channelSpecificDataField");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string AccountBankIMD {
            get {
                return this.accountBankIMDField;
            }
            set {
                this.accountBankIMDField = value;
                this.RaisePropertyChanged("AccountBankIMD");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string AccountNumber {
            get {
                return this.accountNumberField;
            }
            set {
                this.accountNumberField = value;
                this.RaisePropertyChanged("AccountNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string AccountType {
            get {
                return this.accountTypeField;
            }
            set {
                this.accountTypeField = value;
                this.RaisePropertyChanged("AccountType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string AccountCurrency {
            get {
                return this.accountCurrencyField;
            }
            set {
                this.accountCurrencyField = value;
                this.RaisePropertyChanged("AccountCurrency");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string IBAN {
            get {
                return this.iBANField;
            }
            set {
                this.iBANField = value;
                this.RaisePropertyChanged("IBAN");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://TitleFetchService")]
    public partial class TitleFetchDetails : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string accountBankIMDField;
        
        private string accountNumberField;
        
        private string accountTypeField;
        
        private string accountCurrencyField;
        
        private string iBANField;
        
        private string accountTitleField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string AccountBankIMD {
            get {
                return this.accountBankIMDField;
            }
            set {
                this.accountBankIMDField = value;
                this.RaisePropertyChanged("AccountBankIMD");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string AccountNumber {
            get {
                return this.accountNumberField;
            }
            set {
                this.accountNumberField = value;
                this.RaisePropertyChanged("AccountNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string AccountType {
            get {
                return this.accountTypeField;
            }
            set {
                this.accountTypeField = value;
                this.RaisePropertyChanged("AccountType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string AccountCurrency {
            get {
                return this.accountCurrencyField;
            }
            set {
                this.accountCurrencyField = value;
                this.RaisePropertyChanged("AccountCurrency");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string IBAN {
            get {
                return this.iBANField;
            }
            set {
                this.iBANField = value;
                this.RaisePropertyChanged("IBAN");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string AccountTitle {
            get {
                return this.accountTitleField;
            }
            set {
                this.accountTitleField = value;
                this.RaisePropertyChanged("AccountTitle");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://TitleFetchService")]
    public partial class TitleFetchResultType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string responseCodeField;
        
        private string responseDescriptionField;
        
        private TitleFetchDetails dataField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string ResponseCode {
            get {
                return this.responseCodeField;
            }
            set {
                this.responseCodeField = value;
                this.RaisePropertyChanged("ResponseCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string ResponseDescription {
            get {
                return this.responseDescriptionField;
            }
            set {
                this.responseDescriptionField = value;
                this.RaisePropertyChanged("ResponseDescription");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public TitleFetchDetails Data {
            get {
                return this.dataField;
            }
            set {
                this.dataField = value;
                this.RaisePropertyChanged("Data");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://TitleFetchService")]
    public partial class TitleFetchResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private TitleFetchResultType titleFetchResultField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public TitleFetchResultType TitleFetchResult {
            get {
                return this.titleFetchResultField;
            }
            set {
                this.titleFetchResultField = value;
                this.RaisePropertyChanged("TitleFetchResult");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TitleFetchRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://TitleFetchService", Order=0)]
        public MalawiAdapter.TitleFetchService.TitleFetch TitleFetch;
        
        public TitleFetchRequest() {
        }
        
        public TitleFetchRequest(MalawiAdapter.TitleFetchService.TitleFetch TitleFetch) {
            this.TitleFetch = TitleFetch;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TitleFetchResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://TitleFetchService", Order=0)]
        public MalawiAdapter.TitleFetchService.TitleFetchResponse TitleFetchResponse;
        
        public TitleFetchResponse1() {
        }
        
        public TitleFetchResponse1(MalawiAdapter.TitleFetchService.TitleFetchResponse TitleFetchResponse) {
            this.TitleFetchResponse = TitleFetchResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface TitleFetchServiceChannel : MalawiAdapter.TitleFetchService.TitleFetchService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TitleFetchServiceClient : System.ServiceModel.ClientBase<MalawiAdapter.TitleFetchService.TitleFetchService>, MalawiAdapter.TitleFetchService.TitleFetchService {
        
        public TitleFetchServiceClient() {
        }
        
        public TitleFetchServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TitleFetchServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TitleFetchServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TitleFetchServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MalawiAdapter.TitleFetchService.TitleFetchResponse1 MalawiAdapter.TitleFetchService.TitleFetchService.TitleFetch(MalawiAdapter.TitleFetchService.TitleFetchRequest request) {
            return base.Channel.TitleFetch(request);
        }
        
        public MalawiAdapter.TitleFetchService.TitleFetchResponse TitleFetch(MalawiAdapter.TitleFetchService.TitleFetch TitleFetch1) {
            MalawiAdapter.TitleFetchService.TitleFetchRequest inValue = new MalawiAdapter.TitleFetchService.TitleFetchRequest();
            inValue.TitleFetch = TitleFetch1;
            MalawiAdapter.TitleFetchService.TitleFetchResponse1 retVal = ((MalawiAdapter.TitleFetchService.TitleFetchService)(this)).TitleFetch(inValue);
            return retVal.TitleFetchResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MalawiAdapter.TitleFetchService.TitleFetchResponse1> MalawiAdapter.TitleFetchService.TitleFetchService.TitleFetchAsync(MalawiAdapter.TitleFetchService.TitleFetchRequest request) {
            return base.Channel.TitleFetchAsync(request);
        }
        
        public System.Threading.Tasks.Task<MalawiAdapter.TitleFetchService.TitleFetchResponse1> TitleFetchAsync(MalawiAdapter.TitleFetchService.TitleFetch TitleFetch) {
            MalawiAdapter.TitleFetchService.TitleFetchRequest inValue = new MalawiAdapter.TitleFetchService.TitleFetchRequest();
            inValue.TitleFetch = TitleFetch;
            return ((MalawiAdapter.TitleFetchService.TitleFetchService)(this)).TitleFetchAsync(inValue);
        }
    }
}
